### ISSUE TITLE
Starting the app does nothing

### ISSUE THREAD

**Issue by cpele** [Jaysce/Spaceman#19]
When I start the app (installed via Brew) nothing happens. No window, no item in the menu bar, no icon in the Dock. In the Activity Monitor there is a process running, but nothing else.

NB: I tried WhichSpace too as Spaceman is based on it, and WhichSpace works.

I have a M1 MacBook Pro.

**Comment by Jaysce** [comment]
It could be that you have a lot of spaces and a lot of other menu bar apps in the menu bar and Spaceman is too large to fit in the menu bar, resulting it in being hidden. Could you check if this is the case?

**Comment by kevin39** [comment]
Same behavior here but I'have a lot of spaces (6 spaces on monitor 1 / 9 spaces on monitor 2).
Any workaround ?

**Comment by cpele** [comment]
@Jaysce You're right I had 5 spaces and when I delete them I see the app in the menu bar

**Comment by noamsiegel** [comment]
My issue is that after downloading the dmg, starting the application does nothing whatsoever. No menu bar icon as well, even though the process is running in the background confirmed by my activity monitor.

I tried uninstalling/reinstalling it, as well as the homebrew install. None seem to be able to open the application.
