### ISSUE TITLE
Ventura Compatibility?

### ISSUE THREAD

**Issue by CharPatton** [Jaysce/Spaceman#24]
Awesome app; thank you!!!

Any hope of getting an update that will work with Ventura?

**Comment by Jaysce** [comment]
The app should already work with Ventura. What kind of problems are you seeing?

**Comment by CharPatton** [comment]
Hi Sasindu:

 

Thanks for taking the time to reply, and for coding such a nifty little app!

 

I had some issues with upgrading to Ventura, but after a reinstall of 13.3.1 and some restarts, Spaceman is working fairly well now. The only issue I’ve noted is that it doesn’t play optimally with Bartender, but I’ve found some work arounds for that.

 

Again, thank you for coding such a fun and useful piece of software!

 

All the best. Tom

 

On 4/2/23, 23:27, "Sasindu Jayasinghe" ***@***.***> wrote:

 

The app should already work with Ventura. What kind of problems are you seeing?
