### ISSUE TITLE
Cannot set space name for fullscreen space. Always reads 'FUL'

### ISSUE THREAD

**Issue by narbodon** [Jaysce/Spaceman#3]
It seems that fullscreen spaces are not able to have a name set. Please see screenshots for reference. In this example, I have successfully named the middle space 'DEV' and want to name the first space 'SEG,' but 'FUL' remains.

If this is a design constraint, trying to answer the question, "How do you indicate fullscreen with a named space?" then perhaps you could apply the corner chevrons like with rectangle spaces? It would be very beneficial (almost a requisite for usefulness) to be able to name fullscreen spaces. Knowing that they're fullscreen alone doesn't much help the user who wants names. Or put another way, not being able to name fullscreen spaces defeats the purpose of named spaces, if you get my meaning.

<img width="179" alt="Screen Shot 2020-12-24 at 12 04 14" src="https://user-images.githubusercontent.com/6134231/103100516-e9a7a100-45e0-11eb-8a9b-cdc16c825d7b.png">

<img width="512" alt="Screen Shot 2020-12-24 at 12 04 27" src="https://user-images.githubusercontent.com/6134231/103100521-f75d2680-45e0-11eb-9ccc-4dfa99ba1cf9.png">

**Comment by Jaysce** [comment]
This is now fixed in version 0.94

**Comment by narbodon** [comment]
Thanks!
